import json
T=" *(Amended 2026-09-26 after WP2, `PHASE_PORTS_REVIEW.md` WP2.)*"
E=[
["exempt in rate solves. So a draining port lands its phase at the reserve on a step boundary instead of past it.",
 "exempt in rate solves. So a draining port lands its phase at the reserve on a step boundary instead of past it. *Measured in WP2: only where one step spans the band. Under the state-change controller's short steps a draining port closes at the first step start below `phi_open` and keeps its phase in [`phi_reserve` - drift, `phi_open`) (0.99 % on the drained water tank); the throttle is a per-step floor. `dt` is the solve's step (the backward-Euler step attempted, never the slice); `n` counts the vessel's ends of that phase whose connection may carry outflow by the static rule; the throttle is also off while a device holds `PUMP_TARGET` (as the filter room limit), and the pass's start flows are clamped to it (decisions A14, A15).*"+T],
["so it cannot open and close on alternate steps by itself. It needs no carried state, which keeps certified replay free of a new history input (8.9 (b)).",
 "so it cannot open and close on alternate steps by itself. It needs no carried state, which keeps certified replay free of a new history input (8.9 (b)). *WP2: since the port usually closes just below `phi_open`, a port fed while it drains duty-cycles about `phi_open` (measured: 45 transitions in 300 s at 0.1 s slices, 9 at 5 s, no failure; R1). Hysteresis in the committed endpoint mode is the owner's option (review WP2, section 10).*"+T],
["- `reachableComponents` (`:611-612`), `startPoint`'s junction propagation (`:991`) and the approximation probe (`:568`) stop sending material out of an unavailable port.",
 "- `reachableComponents` (`:611-612`), `startPoint`'s junction propagation (`:991`) and the approximation probe (`:568`) stop sending material out of an unavailable port.\n- *also the two other `boundaryAllowed` readers, `initialPhaseSeeds` and the balanced junction seed, and the boundary-reopen test `reopenable`, all on the one start-state mask (`PassiveStepSolver.closedPorts`).*"+T],
["| The throttle lands the phase at the reserve on a step boundary. While closed,",
 "| The throttle keeps every step's draw above the reserve (it lands the phase on the reserve only where one step spans the band; otherwise the port closes at the first step start below `phi_open`; WP2). While closed,"],
["the liquid lands within [`phi_reserve`, `phi_reserve` + flash drift] of the vessel volume,",
 "the liquid lands within [`phi_reserve`, `phi_reserve` + flash drift] of the vessel volume *(WP2: within [`phi_reserve` - flash drift, `phi_open`); on the reserve only where one step spans the band, tested separately at step level)*"+T+","],
["once `phi_l >= phi_open` the same port drains when the generator is lowered below the tank. Run at 5 s slices, with the basis plan's `boundaryReopen`.",
 "once `phi_l >= phi_open` the same port drains when the generator is lowered below the tank. Run at 5 s slices, with the basis plan's `boundaryReopen`. *WP2: a generator refuses inflow, so the draining half runs the port into a junction fed by the generator and drained to a void; the reopen half is a generator line dead-headed at the step start (the tank above the generator, venting below it within the step), and a tank-to-tank run the port alone refuses.*"+T],
["| WP2 | Phase-absent state (3.4): availability in `boundaryAllowed`, throttle, key, `boundaryReopen` link allowance. |",
 "| WP2 | Phase-absent state (3.4): availability in `boundaryAllowed`, throttle, key, `boundaryReopen` link allowance. **WP2 done 2026-09-26** on branch `claude/phase-ports-compressor`, not merged (commit in `PHASE_PORTS_REVIEW.md` WP2 section 12): `PhasePortClosureTest` 15/15 (fixtures 2 and 3 at 5 s and 0.1 s, the throttle, the vanishing phase), fluid suites 428/428 with the junction lines bitwise, exact regression 0.000e+00, 38/38 adjacent, GameTest and mcpCompat sources compile; the band lands just below `phi_open` (section 3.4 amendment, owner options in the review). |"],
["The residual risk is a vessel whose flash moves the phase across the band every step, for example a boiling bottom port under a pressure swing: then the port duty-cycles, but it does not fail. Fixture 2 counts transitions.",
 "The residual risk is a vessel whose flash moves the phase across the band every step, for example a boiling bottom port under a pressure swing: then the port duty-cycles, but it does not fail. Fixture 2 counts transitions. *WP2 measured: fixture 2 has exactly one transition; but since a draining port closes just below 1 % rather than at 0.5 %, a port fed while it drains duty-cycles about `phi_open` (scratch probe: 45 transitions in 300 s at 0.1 s slices, 9 at 5 s, 5 at 1 s steps; no nonconvergence, no held slice).*"+T],
["WP2 measures rejections per slice in fixtures 2 and 5. If they are not rare, the throttle becomes a per-vessel constraint row (one new row per vessel with phase ports, no longer \"no new row\").",
 "WP2 measures rejections per slice in fixtures 2 and 5. If they are not rare, the throttle becomes a per-vessel constraint row (one new row per vessel with phase ports, no longer \"no new row\"). *WP2 measured (review WP2 section 4): no rejection came from the throttle or an overdraw; the rejections are state-change halvings, the BROKEN 3' reopen cost of water entering a dry gas tank, and 2 equation-gate halvings with a VAPOR vent that the WP1 tree shows too (4). The constraint row is not needed.*"+T],
["the availability mask must be passed in and must be the start state's in both.",
 "the availability mask must be passed in and must be the start state's in both. *Resolved in WP2: `PassiveStepSolver.closedPorts(graph)` on the step's start graph, read by every `boundaryAllowed` caller including `reopenable`; the mask enters `WorkspaceKey`.*"+T],
]
json.dump(E,open("/tmp/claude-0/-home-user-CreateChemE/cfcc6b94-4f24-5f12-ba62-46e9aaaec421/scratchpad/wp2/e5.json","w"))
