// WP5 paced tables: transient100 base/on pairs (three each, 60 s + 60 s) with run-to-run ranges, and the module
// profile off/on. Reads wp5-logs/paced/reports/<runId>/report.json. Usage: node paced.js > ../wp5-logs/paced/paced-tables.md
const fs = require('fs'), path = require('path');
const dir = path.resolve(__dirname, '..', 'wp5-logs', 'paced', 'reports');
const load = id => { for (const x of [id, id + '-rerun']) { const f = path.join(dir, x, 'report.json'); if (fs.existsSync(f)) return JSON.parse(fs.readFileSync(f, 'utf8')); } return null; };
const f = (v, d = 3) => v === null || v === undefined || Number.isNaN(v) ? 'n/a' : Number(v).toFixed(d);
const METRICS = [
  ['accepted intervals / s', r => r.completedIntervalsPerSecond ?? r.equivalentFiveSecondIntervalsPerSecond, 3],
  ['ready-to-publication p50 ms', r => r.readyToPublicationMilliseconds.median, 2],
  ['ready-to-publication p95 ms', r => r.readyToPublicationMilliseconds.p95, 2],
  ['ready-to-publication max ms', r => r.readyToPublicationMilliseconds.max, 2],
  ['dispatch-to-publication p50 ms', r => r.dispatchToPublicationMilliseconds.median, 2],
  ['dispatch-to-publication p95 ms', r => r.dispatchToPublicationMilliseconds.p95, 2],
  ['worker p50 ms', r => r.workerMilliseconds.median, 2],
  ['worker p95 ms', r => r.workerMilliseconds.p95, 2],
  ['engine server ms per tick p50', r => r.engineServerMillisecondsPerTick.median, 4],
  ['engine server ms per tick p95', r => r.engineServerMillisecondsPerTick.p95, 4],
  ['engine server ms per tick max', r => r.engineServerMillisecondsPerTick.max, 3],
  ['whole tick ms p50', r => r.wholeTickMilliseconds.median, 4],
  ['whole tick ms p95', r => r.wholeTickMilliseconds.p95, 4],
  ['mean worker CPU occupancy', r => r.meanWorkerCpuOccupancy, 4],
  ['held intervals window / warm-up', r => `${r.heldIntervals} / ${r.warmupHeldIntervals}`, null],
  ['component / energy balance units', r => `${Number(r.componentBalanceToleranceUnits).toExponential(2)} / ${Number(r.energyBalanceToleranceUnits).toExponential(2)}`, null],
  ['integrity passed', r => String(r.stressIntegrityPassed), null],
  ['measured s (configured)', r => `${f(r.measuredSeconds, 1)} (${r.measurementSecondsConfigured ?? 'not in the eb28fc5 report; -PfluidStressMeasurementSeconds=60'})`, null],
];
let out = '# WP5 paced harness tables (generated by wp5-rig/paced.js)\n\n';
const base = ['01', '02', '03'].map(n => `transient100-wp5-base-r${n}`), on = ['01', '02', '03'].map(n => `transient100-wp5-on-r${n}`);
const rb = base.map(load), ro = on.map(load);
out += '## transient100, 60 s warm-up + 60 s window, 12 automatic workers\n\nbase = `fluid-baseline-eb28fc5` (eb28fc5), on = branch with `-PfluidRestDetection=true`.\n\n';
out += '| metric | ' + base.map((id, i) => `base r0${i + 1}`).join(' | ') + ' | ' + on.map((id, i) => `on r0${i + 1}`).join(' | ') + ' | base range | on range | ranges overlap |\n|---|' + '---|'.repeat(9) + '\n';
for (const [label, get, d] of METRICS) {
  const a = rb.map(r => r ? get(r) : null), b = ro.map(r => r ? get(r) : null);
  if (d === null) { out += `| ${label} | ${a.join(' | ')} | ${b.join(' | ')} | | | |\n`; continue; }
  const na = a.filter(v => v != null), nb = b.filter(v => v != null);
  const ra = na.length ? [Math.min(...na), Math.max(...na)] : null, rbb = nb.length ? [Math.min(...nb), Math.max(...nb)] : null;
  const overlap = ra && rbb ? (ra[0] <= rbb[1] && rbb[0] <= ra[1] ? 'yes' : 'no') : 'n/a';
  out += `| ${label} | ${a.map(v => f(v, d)).join(' | ')} | ${b.map(v => f(v, d)).join(' | ')} | ${ra ? f(ra[0], d) + ' to ' + f(ra[1], d) : 'n/a'} | ${rbb ? f(rbb[0], d) + ' to ' + f(rbb[1], d) : 'n/a'} | ${overlap} |\n`;
}
const runs = [...base, ...on].map(id => ({id, r: load(id)}));
out += '\n| run | artifact SHA-256 (prefix) |\n|---|---|\n';
for (const {id, r} of runs) out += `| ${id} | ${r ? String(r.manifest && (r.manifest.productionArtifactSha256 || r.manifest.artifactSha256 || '')).slice(0, 16) : 'missing'} |\n`;
out += '\n## module profile (interval count: 120 s warm-up, then 200 accepted intervals per island), branch, certificates off / on\n\n';
const mo = load('module-wp5-off-r01'), mn = load('module-wp5-on-r01');
out += '| metric | off | on |\n|---|---|---|\n';
if (mo || mn) {
  for (const [label, get, d] of METRICS) out += `| ${label} | ${mo ? (d === null ? get(mo) : f(get(mo), d)) : 'n/a'} | ${mn ? (d === null ? get(mn) : f(get(mn), d)) : 'n/a'} |\n`;
  for (const [label, get] of [['status / gates passed', r => `${r.status} / ${r.gatesPassed}`], ['module committed ticks', r => JSON.stringify(r.moduleCommittedTicks)], ['pending transfer records', r => r.pendingTransferRecords], ['planned capacity records', r => r.plannedCapacityRecords],
    ['full solves / replayed / identity-advanced intervals', r => r.certificates ? `${r.certificates.fullSolves} / ${r.certificates.replayedIntervals} / ${r.certificates.restedIntervals}` : 'n/a'], ['final island kinds', r => r.certificates ? JSON.stringify(r.certificates.finalIslandKinds) : 'n/a'], ['elapsed s', r => f(r.elapsedSeconds, 0)]])
    out += `| ${label} | ${mo ? get(mo) : 'n/a'} | ${mn ? get(mn) : 'n/a'} |\n`;
}
out += '\nStart and end times of every paced run, with the machine gate before each, are in `wp5-logs/paced/campaign.log`.\n';
process.stdout.write(out);
