// Assembles documentation/fluid-scheduler/wp5-tables.md from the run summaries, the generated pair tables and the
// paced tables. Usage: node build-tables.js
const fs = require('fs'), path = require('path'), cp = require('child_process');
const rig = __dirname, root = path.resolve(rig, '..'), logs = path.join(root, 'wp5-logs');
const run = (script, arg) => cp.execFileSync(process.execPath, [path.join(rig, script), ...(arg ? [arg] : [])], {encoding: 'utf8'});
const get = id => { const f = path.join(logs, id, 'summary.json'); return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : null; };
const pairs = run('tables.js');
const serverPart = pairs.split('## Integrated client')[0].split('## Dedicated server (no rendering in the JVM)')[1];
const clientPart = pairs.split('## Integrated client (rendering and integrated server in one JVM)')[1].split('## Soak')[0];
const soakPart = pairs.split('## Soak (branch, dedicated server, 60 s warm-up + 300 s window)')[1] || '';
let out = `# Fluid scheduler WP5 tables

Date: 2026-09-23. Branch \`claude/fluid-scheduler\` (rig commits \`36caef6\`, \`39aabac\` on top of WP4's \`3b6f206\`); baseline \`fluid-baseline-eb28fc5\` at \`eb28fc5\` with the uncommitted rig patch (\`wp5-rig/baseline-rig/\`). Generated by \`wp5-rig/build-tables.js\` from \`wp5-logs/<run-id>/summary.json\` (\`wp5-rig/analyze.js\`) and \`wp5-logs/paced/reports/\` (\`wp5-rig/paced.js\`).

**Windows: every in-game run 60 s warm-up after placement + 60 s measured (soaks 60 s + 300 s); paced \`transient100\` 60 s + 60 s; \`module\` 120 s warm-up + 200 intervals per island.** Machine: AMD Ryzen 7 9700X (8 cores, 16 threads), 48 GB, Windows 11; every run started with no \`Endfield.exe\` and at least 20 GB free (\`wp5-logs/campaign.log\`, \`wp5-logs/paced/campaign.log\`). Game JVMs: JDK 21.0.11, \`-Xmx4096m\`, \`-Xshare:off\` on Gradle; 12 automatic solver workers; default \`createcheme-common.toml\` (adaptive cadence on).

## 1. Dedicated server, before (eb28fc5) and after (branch)
${serverPart}
## 2. Integrated client, before and after
${clientPart}
## 3. Compact comparison

${run('compact.js', 'server')}
${run('compact.js', 'client')}
${run('compact.js', 'ratios')}
## 4. Scheduling counters summed over the window (fluid_diag, both builds)

| run | island visits | topology snapshots | readiness pumps | solves dispatched | islands published | deadlines fired | view builds | device presentations | bucket flushes | certificates issued | materialisations | drain continuations |
|---|---|---|---|---|---|---|---|---|---|---|---|---|
`;
const ids = fs.readdirSync(logs).filter(d => /^(srv|cli)-.*-r0\d$/.test(d) && fs.existsSync(path.join(logs, d, 'summary.json'))).sort();
for (const id of ids) {
  const c = get(id).diagCountersInWindow || {};
  out += `| ${id} | ${['islandVisits', 'topologySnapshots', 'readinessPumps', 'solvesDispatched', 'islandsPublished', 'deadlinesFired', 'viewBuilds', 'devicePresentations', 'bucketFlushes', 'certificatesIssued', 'materialisations', 'drainContinuations'].map(k => c[k] || 0).join(' | ')} |\n`;
}
out += `\neb28fc5 has no deadlines, presentation buckets or certificates, and its counters predate the device-presentation counter (added in WP3), so those columns are zero there by construction; its view builds are the publication-driven refreshes of loaded devices.\n\n## 5. Repeats of the held-retry scenarios (dedicated server)\n\n${run('compact.js', 'repeats')}\n## 6. Soak (branch, dedicated server, 60 s warm-up + 300 s window)\n${soakPart}\n## 7. Placement (one datapack function; RCON round trip on the server, chat round trip in the client, and the longest gap between two server ticks)\n\n| run | devices | function ms | tick gap ms |\n|---|---|---|---|\n`;
for (const id of ids) { const s = get(id); if (!s.endState || !s.endState.devices) continue; out += `| ${id} | ${s.endState.devices} | ${s.placementMillis ?? 'n/a'} | ${s.placementGap ? s.placementGap.ms.toFixed(0) : 'n/a'} |\n`; }
out += `\nThe client's function time includes the chat round trip and reply polling (250 ms steps).\n\n## 8. Probes and pilots (branch unless named, dedicated server except \`pilot-cli-*\`)\n\n| run | content | window | outcome |\n|---|---|---|---|\n`;
const probes = [
  ['probe-r01', '1 closed line, 2 vessel-free pumped through lines, 4 vessel through lines, 8 pumped six-tank fills, 16 level generator-to-void lines (237 devices)', '360 s + 30 s', 'REST 17, STEADY 2, FULL 4, HELD 8 from 20 s to the end; 493 held retries'],
  ['probe2-r01', 'pumped fills into 1, 2, 3 tanks (1, 2, 4), six tanks (8); gravity fills, 1 tank (16), 3 tanks (32) (480 devices)', '300 s + 20 s', 'one-tank gravity lines REST by 60 s; three-tank gravity lines STEADY between 150 and 300 s; six-tank fills held throughout; 901 held retries'],
  ['probe3-r01', 'pump transfers tank to tank, tank to two tanks, two to two (8 each, 144 devices)', 'stopped at 70 s', 'all 24 held ("interval substep limit")'],
  ['probe4-r01', 'pumped water through 3 or 6 tanks vented to a void (8, 8), vessel through lines (8) (264 devices)', 'stopped at 200 s', 'through lines FULL; 12 of 16 vented chains held'],
  ['pilot-fill100-r01', 'fill100 with three-tank chains', '60 s + 60 s', '12.3 cores, 88 held then 23 FULL at the end; Minecraft /jfr profile: 18 heap-inspection full GCs in the window'],
  ['pilot-through100-r01', 'through100', '60 s + 60 s', 'FULL 100 throughout'],
  ['pilot-rest100-r01', 'rest100 (first window recording with wp5-window.jfc)', '60 s + 60 s', 'REST 100'],
  ['pilot-rest100-base-r01', 'rest100 on eb28fc5 (first baseline build)', '60 s + 60 s', 'AWAKE 100, FULL 100'],
  ['pilot-cli-fill100-r02', 'fill100 in the client (driver with chat commands)', '60 s + 60 s', 'devices 800, islands 100 registered; FULL 27, HELD 61, SOLVING 12 at the end; F3 screenshot 119 fps'],
];
for (const p of probes) out += `| ${p.join(' | ')} |\n`;
const paced = path.join(logs, 'paced', 'paced-tables.md');
out += `\nThe first client pilot (\`pilot-cli-rest100-r01\`, 20:24 local) failed: every command sent with the bridge's \`execute_command\` was refused client-side ("Unknown or incomplete command"); it was stopped and its directory removed, and the driver types commands into chat since.\n\n## 9. Paced harness\n\n${fs.existsSync(paced) ? fs.readFileSync(paced, 'utf8').replace(/^# .*\n/, '').replace(/^## /gm, '### ') : '(not yet run)'}\n`;
const gates = path.join(rig, 'gates-section.md');
out += `\n## 10. Gates\n\n${fs.existsSync(gates) ? fs.readFileSync(gates, 'utf8') : '(not yet run)'}\n`;
fs.writeFileSync(path.join(root, 'wp5-tables.md'), out);
console.log('wrote wp5-tables.md', out.length);
